### PR TITLE
Minor fixes to setup script and Dockerfile

### PR DESCRIPTION
**Pull request by dposada**
... plus a `.gitignore`, making the scripts under `/bin` executable, and adding `sample_launch.sh`, which was expected by the Dockerfile to exist.

### CODE REVIEW

**Comment by dposada** [comment]
@wyegelwel I'm assuming the `sample_launch.sh` here should be the same one as in https://github.com/twosigma/Cook/tree/master/scheduler/bin, but I'm happy to change it if not

**Comment by wyegelwel** [comment]
Yea I think the only change I have on that script is to generate new uuid on each submission.

**Comment by wyegelwel** [comment]
Happy to merge as is

**Comment by dposada** [comment]
No problem, I will modify the script to generate a new uuid each time

**Comment by dposada** [comment]
Looks like the sample launch is also missing priority, which is required. I will add.

**Comment by dposada** [comment]
Added uuid generation, priority, and name to the sample launch script

**Comment by dposada** [comment]
@wyegelwel Thoughts on this?

**Comment by betehess** [comment]
This all worked for me. 👍 on merging that in!

**Pull request merged**
